apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: '{{ include "hnc.fullname" . }}-mutating-webhook-configuration'
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: '{{ include "hnc.fullname" . }}-webhook-service'
        namespace: '{{ include "hnc.namespace" . }}'
        path: /mutate-namespace
    failurePolicy: Ignore
    name: namespacelabel.hnc.x-k8s.io
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - namespaces
    sideEffects: None
