apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
    prometheus.io/scrape: "true"
  labels:
    control-plane: controller-manager
  name: '{{ include "hnc.fullname" . }}-controller-manager-metrics-service'
  namespace: '{{ include "hnc.namespace" . }}'
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    control-plane: controller-manager
