# Automatically aggregated to clusterRoles: cluster-reader, view -> edit -> admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - hnc.x-k8s.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch